### PR TITLE
Allow custom container port

### LINKED ISSUE #48: Allow user to specify target port for a core/knative Deployer
Currently we force the use of port 8080

### PR DESCRIPTION
**Pull request by scothis**
Previously the runtime assumed port 8080. Now the port may be defined in
the container's ContainerPorts list. The containers first port is used
when defaulting probes and creating the fronting service mapping.

The PORT envvar is now set on the first container of the Deployment.
This envvar is prohibited from being set directly on the Deployer as it
will be injected.

8080 is still used by default.

Resolves #48

### CODE REVIEW

**Comment by trisberg** [comment]
Not sure setting PORT works as expected for boot apps.

Applying this:

```
apiVersion: core.projectriff.io/v1alpha1
kind: Deployer
metadata:
  name: upper
  namespace: default
spec:
  template:
    containers:
    - image: trisberg/upper
      name: "upper"
      ports:
      - name: "http"
        protocol: TCP
        containerPort: 8081
```

and getting:

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::             (v2.2.0.M6)

18:33:05.787 [main] INFO  i.p.invoker.main.EntryPoint - Starting EntryPoint on upper-deployer-7sx54-d84f8668c-7nztf with PID 15 (/layers/io.projectriff.java/riff-invoker-java/BOOT-INF/classes started by cnb in /workspace)
18:33:05.793 [main] INFO  i.p.invoker.main.EntryPoint - No active profile set, falling back to default profiles: default
18:33:08.072 [main] INFO  o.s.c.f.d.FunctionDeployerConfiguration - Deploying archive: /workspace
18:33:08.103 [main] INFO  o.s.c.f.d.FunctionArchiveDeployer - Registering function class 'class functions.Upper' of type 'java.util.function.Function<java.lang.String, java.lang.String>' under name 'upper'.
18:33:08.110 [main] INFO  o.s.c.f.d.FunctionDeployerConfiguration - Successfully deployed archive: /workspace
18:33:08.356 [main] INFO  i.p.invoker.main.EntryPoint - Started EntryPoint in 3.355006687 seconds (JVM running for 4.647)
2019/11/20 18:33:09 error running proxy listen tcp :8081: bind: address already in use
```

**Comment by scothis** [comment]
Try testing with any other port or an application instead of a function. Functions use the streaming-http-adapter which has assumptions that need to be reconsidered. 

https://github.com/projectriff/streaming-http-adapter/blob/4e46633b0ddcb2d51039a849ae56f650cb4e5da7/main.go#L32-L42

**Comment by trisberg** [comment]
Yep, you're right, this worked:

```
apiVersion: core.projectriff.io/v1alpha1
kind: Deployer
metadata:
  name: petclinic
  namespace: default
spec:
  ingressPolicy: External
  template:
    containers:
    - image: trisberg/petclinic
      name: "petclinic"
      ports:
      - name: "http"
        protocol: TCP
        containerPort: 8081
      env:
      - name: SERVER_PORT
        value: '${PORT}'
```

**Comment by trisberg** [comment]
And so did setting the port to `8088` for a function

**Comment by scothis** [comment]
Merging as this change will provide direct benefit to applications, which are the most likely to need to set a custom port. The behavior for functions is no worse than today, and will be on par with application once the streaming adapter is updated.

**Pull request merged**
