### PR TITLE
Kubebuilder (alt)

### PR DESCRIPTION
**Pull request by scothis**
Scaffolding for kubebuilder, alternative to #58 

This setups up kubecbuiler resources and controllers for build, core, knative and streaming components. No domain logic/structure has been created yet.

### CODE REVIEW

**Comment by sbawaska** [comment]
Since kubebuilder does not support multiple groups, I wanted to see how adding a new type would work with this setup. kubebuilder does not seem happy. 😞

```
±  |scott-kubebuilder → scott/kubebuilder ✓| → kubebuilder create api --group build --version v1alpha1 --kind MyNewType
Create Resource [y/n]
y
Create Controller [y/n]
y
Writing scaffold for you to edit...
2019/09/10 08:51:04 Group 'build' is not same as existing group 'knative'. Multiple groups are not supported yet.

  Swapnils-MacBook-Pro in ~/workspace/system
±  |scott-kubebuilder → scott/kubebuilder ✓| → kubebuilder create api --group knative --version v1alpha1 --kind MyNewType
Create Resource [y/n]
y
Create Controller [y/n]
y
Writing scaffold for you to edit...
2019/09/10 08:51:20 Group 'knative' is not same as existing group 'build'. Multiple groups are not supported yet.
```
editing existing types seem to work though.

Until kubebuilder supports multiple groups, I think we should have multiple kubebuilder projects in different folders in the same repo. like #61

**Comment by scothis** [comment]
> Until kubebuilder supports multiple groups I think we should have multiple kubebuilder projects in different folders in the same repo

The value add of scaffolding an incremental resource is low. It's can be done manually by creating a single go file with the new types, and then running `make package`. Proper multi-group support should become available in kubebuilder 2.1.0.

This PR started with four independent kubebuilder projects living in a single repo, but it ended up being a bit unwieldily. Slowly massaging and centralizing the common bits led to the current state.

**Comment by sbawaska** [comment]
If the support for multi-group is going to land in `2.1.0`, I feel good about merging this! 👍

**Comment by scothis** [comment]
> If the support for multi-group is going to land in `2.1.0`, I feel good about merging this! 👍

Not certain, but that's the target. see https://github.com/kubernetes-sigs/kubebuilder/issues/923

**Pull request merged**
