### PR TITLE
Use InMemoryProvider for FATS tests

### PR DESCRIPTION
**Pull request by scothis**
Not using kafka will reduce strain on the test cluster and should speed
up the test.

### CODE REVIEW

**Comment by ericbottard** [comment]
LGTM, maybe we can rename the provider instance to avoid false cognitive assumptions

**Comment by fbiville** [comment]
Rebased and merged as c0581a5e31b7040a690926fa5a57cebde9394dfc

**Comment by scothis** [comment]
This should not have been merged, as the change is failing CI

**Comment by scothis** [comment]
stale

**Pull request closed without merging**
