### PR TITLE
Test streaming functions

### PR DESCRIPTION
**Pull request by scothis**

### CODE REVIEW

**Comment by scothis** [comment]
@sbawaska @ericbottard I've stripped this PR down to the core necessary to run the streaming runtime in CI, and added a bunch of extra logging. The tests are failing because no messages are emitted from the processor. The processor Pod is being shutdown before it starts.

- the KEDA cooldown period is ignored. Jurgen reported a different manifestation of the same issue in #151. Are we doing something wrong, or is there a bug in KEDA? We set the cool down period to 30 seconds.
- are we ACKing the message in the processor sidecar before remitting the message to the function? There should still be lag on the topic until the function is able to handle the message (success or fail). Just because a message is read, doesn't mean that work is complete.

**Comment by ericbottard** [comment]
> the KEDA cooldown period is ignored. Jurgen reported a different manifestation of the same issue in #151. Are we doing something wrong, or is there a bug in KEDA? We set the cool down period to 30 seconds.

We're not doing anything wrong (on the riff side). The keda liiklus scaler (and any scaler in general) doesn't take into account that a scaler should be considered "Active" when there is *progress* (in addition to obvious *lag*). Sadly, to be able to track progress (ie the fact that current offset is further now than it was one tick ago), the scaler API would need to maintain state, which is really not how KEDA is architectured at the moment.

> are we ACKing the message in the processor sidecar before remitting the message to the function? There should still be lag on the topic until the function is able to handle the message (success or fail). Just because a message is read, doesn't mean that work is complete.

We are indeed ACKing the message one-by-one in the processor (for now, because ultimately we'll need to give more control to the function). I'm not sure we can push it down some more (in particular, we can't decide to ACK based on *output*, because there is no one-to-one mapping between function input messages and function outputs)

**Comment by ericbottard** [comment]
That being said, for a function that sees a single message at time t0, it should stay up till t0+30s, even today.

**Comment by ericbottard** [comment]
May be nice to later change the tested function to do things only possible via streaming (eg emit N results) but LGTM in the current form

**Pull request merged**
